name: Build Petclinic Jar
on:
  workflow_dispatch:
    inputs:
      aws_region:
        type: string
        default: 'us-east-2'
        description: 'AWS Region'
        required: true
      upload_to_s3:
        type: boolean
        default: false
        description: 'upload to S3'
        required: false
      mvn_install:
        type: boolean
        default: false
        description: 'maven install'
        required: false
      mvn_test:
        type: boolean
        default: false
        description: 'maven test'
        required: false

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JAVA
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Build with Maven
        if: ${{ inputs.mvn_install == 'true' }}
        run: mvn install -DskipTests

      - name: Maven test
        if: ${{ inputs.mvn_test == 'true' }}
        run: mvn test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Upload to S3
        if: ${{ inputs.upload_to_s3 == 'true' }}
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: afeef-tc-petclinic
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
          SOURCE_DIR: 'jars/*.jar'
          DEST_DIR: 'test/'