name: Build Petclinic Jar
on:
  workflow_dispatch:
    inputs:
      build_jar:
        type: string
        default: 'false'
        description: 'build jar'
        required: false
      aws_region:
        type: string
        default: 'us-east-2'
        description: 'AWS Region'
        required: true
      upload_to_s3:
        type: string
        default: 'false'
        description: 'upload to S3'
        required: false
      mvn_install:
        type: string
        default: 'false'
        description: 'maven install'
        required: false
      mvn_test:
        type: string
        default: 'false'
        description: 'maven test'
        required: false
      dep_env:
        type: string
        default: 'staging'
        description: 'Deploy environment'
        required: false
      dep_role:
        type: string
        default: 'afeefPetclinic'
        description: 'Deploy role'
        required: false
      dep_flavor:
        type: string
        default: 't3.medium'
        description: 'Deploy ec2 instance type'
        required: false
      dep_asg_size:
        type: string
        default: '2'
        description: 'Deploy ASG size'
        required: false
      dep_ami:
        type: string
        default: 'ami-0aeb7c931a5a61206'
        description: 'Deploy ec2 ami'
        required: false

jobs:
  build_jar:
    if: ${{ inputs.build_jar == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JAVA
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Maven install
        if: ${{ inputs.mvn_install == 'true' }}
        run: mvn install -DskipTests

      - name: Maven test
        if: ${{ inputs.mvn_test == 'true' }}
        run: mvn test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Upload to S3
        if: ${{ inputs.upload_to_s3 == 'true' }}
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: afeef-tc-petclinic
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
          SOURCE_DIR: 'jars/'
          DEST_DIR: 'test/'

  deploy:
    runs-on: ubuntu-latest
    container: devopslets/gs-cli-alb:latest_develop
    steps:
      - name: Checkout Deployer code
        uses: actions/checkout@v3
        with:
          repository: AfeefGalil/petclinic_deploy
          ref: master

      - name: Deploy
        run: |
          . /gsdeployer/bin/activate
          PYTHONPATH=. deploy_vpc deploy --env ${{inputs.dep_env}} --role ${{inputs.dep_role}} --bld ${{github.run_number}} --aws-chef-artifact "s3://afeef-tc-petclinic/afeef-chef-29-master.zip" --aws-petclinic-artifact "petclinic-35-afeef-petclinic.jar" --branch ${{github.head_ref}} --flavor ${{inputs.dep_flavor}} --asg-size ${{inputs.dep_asg_size}} --region ${{inputs.aws_region}}  --ami-override ${{inputs.dep_ami}} --on-demand
