name: Build Petclinic Jar
on:
#   push:
#     branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout main branch with Github
        uses: actions/checkout@v3

      - name: Step 2 - Setup JAVA
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: mvn install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: 415102591172.dkr.ecr.us-east-2.amazonaws.com/afeef-petclinic-private
          IMAGE_TAG: ${{ github.GITHUB_RUN_NUMBER }}
        run: |
          docker build -t afeef-petclinic-private:$IMAGE_TAG .
          docker push afeef-petclinic-private:$IMAGE_TAG